### ISSUE TITLE
Data validation fails due to date format

### ISSUE THREAD

**Issue by ialarmedalien** [kbase/credit_engine#151]
The data validation step of the `run_tests.yaml` GitHub action has been disabled due to issues validating the dates.

Example of problematic values:

```yaml
  dates:
    - date: '2020'
      event: issued

    - date: 2020
      event: created

    - date: 2022-05-25
      event: updated
```

TODO: find out which of these values can be correctly parsed and what the appropriate linkml type should be.
